// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // This is the connection the CLI (migrate/db push/studio) uses — always
    // the DIRECT connection. Locally that's the only Postgres there is;
    // against Neon in production, migrations must bypass the pooler, so
    // this must NOT be the pooled URL. The installed @prisma/config version
    // has no `directUrl` field (only `url`/`shadowDatabaseUrl`) — the
    // pooled/direct split is done by keeping the *app's* runtime connection
    // (lib/db.ts, via @prisma/adapter-pg) on a separate env var instead.
    url: process.env["DIRECT_URL"],
  },
});
