import type { Prisma } from "@/lib/generated/prisma/client";

/** One profile per seeded buyer in users.ts, linked by userId. */
export const buyerProfiles: Prisma.BuyerProfileCreateInput[] = [
  {
    id: "bpf_ozola",
    user: { connect: { id: "usr_byr_ozola" } },
    headline: "Search fund targeting licensed EMIs in the Baltics",
    bio: "Ex-Wise operator raising a single-asset search fund. Looking for a licensed EMI or PI with an existing client book to operate directly rather than build from zero.",
    sectors: ["Fintech", "Payments"],
    jurisdictions: ["EE", "LT"],
    budgetMin: 150000,
    budgetMax: 300000,
    dealTypes: ["asset purchase", "share deal"],
  },
  {
    id: "bpf_jankauskas",
    user: { connect: { id: "usr_byr_jankauskas" } },
    headline: "Family office — Baltic lending & payments roll-up",
    bio: "Deploying capital on behalf of a Vilnius-based family office building a consolidated lending and payments group across the Baltics.",
    sectors: ["Lending", "Payments"],
    jurisdictions: ["LT", "LV", "EE"],
    budgetMin: 100000,
    budgetMax: 400000,
    dealTypes: ["share deal"],
  },
  {
    id: "bpf_wozniak",
    user: { connect: { id: "usr_byr_wozniak" } },
    headline: "Boutique PE — Polish regulated financial services",
    bio: "Wozniak Ventures backs founder-led acquisitions of regulated Polish financial services businesses, typically as a minority co-investor alongside operators.",
    sectors: ["Payments", "Wealth Management", "Insurtech"],
    jurisdictions: ["PL"],
    budgetMin: 80000,
    budgetMax: 350000,
    dealTypes: ["asset purchase", "share deal"],
  },
  {
    id: "bpf_larsen",
    user: { connect: { id: "usr_byr_larsen" } },
    headline: "Nordic investment firm, MiFID licenses preferred",
    bio: "Larsen Capital acquires small licensed investment firms across the EU as platforms for a discretionary asset management roll-up.",
    sectors: ["Wealth Management"],
    jurisdictions: ["PL", "EE", "LT"],
    budgetMin: 200000,
    budgetMax: 500000,
    dealTypes: ["share deal"],
  },
  {
    id: "bpf_dubois",
    user: { connect: { id: "usr_byr_dubois" } },
    headline: "Crypto-native fund seeking EU VASP registrations",
    bio: "Post-MiCA, we're consolidating EU VASP registrations for a single passported entity. Open to both license-only and license-plus-ops deals.",
    sectors: ["Crypto"],
    jurisdictions: ["MT", "EE"],
    budgetMin: 250000,
    budgetMax: 600000,
    dealTypes: ["asset purchase"],
  },
  {
    id: "bpf_kask",
    user: { connect: { id: "usr_byr_kask" } },
    headline: "Serial acquirer — Estonian fintech shells",
    bio: "Independent investor, previously acquired and exited two Estonian EMIs. Looking for the next licensed shell, ideally with minimal legacy client exposure.",
    sectors: ["Fintech", "Payments"],
    jurisdictions: ["EE"],
    budgetMin: 100000,
    budgetMax: 250000,
    dealTypes: ["asset purchase"],
  },
  {
    id: "bpf_petraityte",
    user: { connect: { id: "usr_byr_petraityte" } },
    headline: "Vilnius Acquisitions — lending platforms with loan books",
    bio: "We acquire consumer and SME lending platforms in the CEE region, valuing both the license and the existing loan book.",
    sectors: ["Lending"],
    jurisdictions: ["LT", "PL"],
    budgetMin: 120000,
    budgetMax: 300000,
    dealTypes: ["share deal", "asset purchase"],
  },
  {
    id: "bpf_ostrowski",
    user: { connect: { id: "usr_byr_ostrowski" } },
    headline: "Opportunistic buyer, open sector mandate",
    bio: "Ostrowski Capital evaluates licensed financial services opportunities across payments, lending, and insurtech — no fixed sector preference, priced on cash flow.",
    sectors: ["Payments", "Lending", "Insurtech"],
    jurisdictions: ["PL", "LT", "EE"],
    budgetMin: 50000,
    budgetMax: 200000,
    dealTypes: ["asset purchase"],
  },
  {
    id: "bpf_marchetti",
    user: { connect: { id: "usr_byr_marchetti" } },
    headline: "Marchetti Financial Group — Southern Europe expansion via CEE licenses",
    bio: "Italian financial group seeking a passportable EU license to extend our payments product into the Baltics without a from-scratch application.",
    sectors: ["Payments", "Fintech"],
    jurisdictions: ["EE", "LT", "MT"],
    budgetMin: 150000,
    budgetMax: 280000,
    dealTypes: ["asset purchase"],
  },
  {
    id: "bpf_kowalski",
    user: { connect: { id: "usr_byr_kowalski" } },
    headline: "Holdco seeking fast-close licensed entities",
    bio: "Kowalski Holdco — flexible on structure, prioritizing speed to close over price.",
    sectors: ["Payments"],
    jurisdictions: ["PL"],
    budgetMin: 40000,
    budgetMax: 120000,
    dealTypes: ["asset purchase"],
  },
];
